name: Pandoc
on: workflow_dispatch
jobs:
  convert_via_pandoc:
    name: "Build Pull Request PDFs"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: docker://pandoc/latex:3.7.0.2
        with:
          args: >-
            -f gfm
            -t pdf
            -s
            --file-scope=true
            --output=output.pdf
            markdown1.md markdown2.md markdown3.md
      - uses: actions/upload-artifact@v4
        with:
          name: Pandoc Test Output
          path: output.pdf
